name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with: 
          image: fastapi/
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{SECRETS.DOCKER_ID}}
          password: ${{SECRETS.DOCKER_PWD}}
